version: "3.2"
services:
  php:
    # For MAC M1
    platform: linux/x86_64
    build: .
    ports:
      - 8080:80
    depends_on:
      - db
    volumes:
      # Mount source-code for development
      - ./app:/var/www/html
  db:
    # For MAC M1
    platform: linux/x86_64
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    volumes:
      - ./mysqldb:/var/lib/mysql
  pma:
    # For MAC M1
    platform: linux/x86_64
    image: phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8081:80
